image: node:latest

stages:
  - production
  - register

build:production:
  stage: production
  script:
    - npm install
    - npm run prod:build
  artifacts:
    expire_in: 1 weeks
    paths:
      - dist/*.js
      - package.json

build:docker:
  image: docker:latest
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  services:
    - docker:dind
  stage: register
  dependencies:
    - build:production
  script:
    - docker build -t registry.gitlab.com/itglance/dental/dental-api-v2 .
    - docker push registry.gitlab.com/itglance/dental/dental-api-v2
  only:
    - master


